env: # Environment variables to pass to all tasks
    CIRRUS_CLONE_DEPTH: 1 # No need to clone with the whole history
    CIRRUS_WORKING_DIR: "/tmp/ci" # Where to clone the aosp-builder repo

# store our secrets here
    my_og_token: "ENCRYPTED[!4ed450bcbc618a2a68265fdae6590108d7f533cd761d8fb73170e4f477c8ed2efea7f71ba7bfc0ea900312e6a4901952!]" # main id
    github_token: "ENCRYPTED[!2192a667547bf4f72b81dfcf6462f4feede24acb861bbe1d8f75e41259b7130e1ff24462786031d42c4b2c27271e9dd0!]" # alt id
    bot_api: "ENCRYPTED[!3d10c54b189dd7714c3542a647db26b408bb9ec4b4358af9b91b2f95386c4245079e29cd1ca631767f8d12609b1a4dff!]"
    chat_id: "ENCRYPTED[!89372a374bdff7c2762f1be427746e1f1de808ecb6655ae21da807c4a59a87854832e616e2d527478e369e88fc9ad3a4!]"
    git_cookies: 0
    REAL_REPO_OWNER: "ENCRYPTED[!1f20df1282c3d9f1c6507b4889cbdbd57d3dfb6551daf597bedc9e89b149f16a310b410aee9aad06ec23e960ef8c68fd!]" # main id
    REAL_REPO_OWNER: "ENCRYPTED[!22316778a70c4b6a99936158128d7403a6aec600c0c6da27a7b1e82e18318e027df11c1096d4c77de98d81ec61bb0112!]" # main id

# store information about git here
    gmail: ehteshammalik18998@gmail.com

task:
    name: GODZ
    timeout_in: 120m
    container:
      image: nexgang/ubuntu:latest
      cpu: 8
      memory: 32G
      stateful: true
      greedy: true
    down_background_script:
      - git clone -b main https://$REAL_REPO_OWNER:$my_og_token@github.com/projects-nexus/ci-script /tmp/cs
      - mv /tmp/cs/* /tmp/ci
      - bash down*
    symc_script:
      - bash sy*
    compile_script:
      - bash bu*
    upl_script:
      - bash upl*
