#!/bin/bash

. /tmp/ci/builder.sh
cd $KERNEL_DIR

SECONDS=0

# Compile
post_msg " Starting Compilation...! "
export CCACHE_DIR=/tmp/ccache
export CCACHE_EXEC=$(which ccache)
export USE_CCACHE=1
ccache -M 5G
ccache -o compression=true
ccache -z
. /tmp/ci/builder.sh -c

# Check for error and report with logs. if everything fine then upload
. /tmp/ci/builder.sh -err -upl

# Let's print ccache statistics
ccache -s
