#!/bin/bash

. /tmp/ci/builder.sh
cd $KERNEL_DIR

SECONDS=0

#patch
git config --global user.email $gmail
git config --global user.name "wHo-EM-i"
curl https://github.com/projects-nexus/android_xtreme_kernel_lavender/commit/7e8712eb0de9944fe4c4d3fad68eecb661dc0190.patch | git am

# Compile
post_msg " Starting Compilation...! "
export CCACHE_DIR=/tmp/ccache
export CCACHE_EXEC=$(which ccache)
export USE_CCACHE=1
ccache -M 5G
ccache -o compression=true
ccache -z
. /tmp/ci/builder.sh -c

# Check for error and report with logs. if everything fine then upload
. /tmp/ci/builder.sh -err -upl

# Let's print ccache statistics
ccache -s
